[book]
authors = ["Koukyosyumei"]
language = "en"
multilingual = false
src = "src"
title = "MyZKP: Building Zero Knowledge Proof from Scratch"

[output.html]
mathjax-support = true
<<<<<<< HEAD
additional-css = ["theme/css/custom.css"]
=======
>>>>>>> main
